server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    #active: aggregation
     active: dev
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务器地址
        username: nacos              # 用户名
        password: nacos              # 密码
